# static_map - True if using existing map

global_costmap:
  global_frame: map         #odom initial
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 1.0
#resolution: 0.05
  static_map: true
  
  plugins:
  - {names: static,                      type: "costmap_2d::StaticLayer"}
  - {names: obstacles_layer,             type: "costmap_2d::VoxelLayer"}
  - {names: inflation_layer,             type: "costmap_2d::InflationLayer"}
  
