TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.2
  max_vel_theta: 0.6 #0.45
  min_vel_theta: -0.6 #-0.45
  min_in_place_vel_theta: 0.25

  acc_lim_theta: 0.25
  acc_lim_x: 2.5
  acc_lim_Y: 2.5

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.15 #0.15
  yaw_goal_tolerance: 0.25 # 0.25